movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search_result/', views.SearchResultView.as_view(), name='search_result'),
    path("country_list/", views.CountryListView.as_view(), name="country_list"),
    path("country_detail/<int:pk>", views.CountryDetailView.as_view(), name="country_detail"),
    path("movie_list/", views.MovieListView.as_view(), name="movie_list"),
    path("movie_detail/<int:pk>", views.MovieDetailView.as_view(), name="movie_detail")
]

movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movieapp/', include('movieapp.urls')),
    path('', RedirectView.as_view(url='movieapp')),

]

movieapp/models.py
from django.db import models


# Create your models here.


class Country(models.Model):
    common = models.CharField(max_length=100)
    official = models.CharField(max_length=100)
    capital = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    subregion = models.CharField(max_length=100, null=True, blank=True)
    flag = models.CharField(max_length=100)
    map = models.CharField(max_length=100)

    class Meta:
        """ Default result ordering """
        ordering = ['common']
        verbose_name_plural = 'countries'

    def country_info(self):
        """Show simple book info """
        return f'{self.common}, {self.official}'

    def __str__(self):
        """ Admin page show info """
        return self.common


class Movie(models.Model):
    title = models.CharField(max_length=100)
    year = models.CharField(max_length=100)
    imdb = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    poster = models.CharField(max_length=100)

    class Meta:
        """ Default result ordering """
        ordering = ['title']
        verbose_name_plural = 'movies'

    def country_info(self):
        """Show simple book info """
        return f'{self.title}, {self.year}'

    def __str__(self):
        """ Admin page show info """
        return self.title

movieapp/views.py
import urllib.parse
from urllib.request import urlopen
import json

from django.views.generic import TemplateView, ListView, DetailView
from django.conf import settings
from .models import *

# Create your views here.


class HomeView(TemplateView):
    template_name = 'movieapp/index.html'


class SearchView(TemplateView):
    template_name = 'movieapp/search.html'


class SearchResultView(ListView):
    model = Country
    template_name = 'movieapp/search_result.html'
    table = None  # (country, movie, None)

    def get_queryset(self):
        object_list = []
        # form input:text->name="search"
        query = self.request.GET.get("search")
        # form select:name= 'table'
        self.table = self.request.GET.get("table")

        if self.table == 'country':
            # search from table of country
            object_list = Country.objects.filter(common__icontains=query)
        elif self.table == 'movie':
            value = urllib.parse.quote_plus(query)
            search = 's=' + value  # what search
            result = '&'.join([settings.OMDB_URL, search])
            print(result)
            response = urlopen(result)
            data = json.loads(response.read())
            if data['Response'] == 'True':
                for obj in data['Search']:
                    object_list.append(obj)
                    Movie.objects.get_or_create(title=obj['Title'], year=obj['Year'], imdb=obj['imdbID'],
                                                type=obj['Type'], poster=obj['Poster'])

        return object_list  # return search result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['table'] = self.table
        return context


class CountryListView(ListView):
    model = Country
    queryset = Country.objects.order_by('common')
    context_object_name = 'countries'
    paginate_by = 10


class CountryDetailView(DetailView):
    model = Country


class MovieListView(ListView):
    model = Movie
    queryset = Movie.objects.order_by("title")
    context_object_name = "movies"
    paginate_by = 10


class MovieDetailView(DetailView):
    model = Movie

movieapp/templates/movieapp/country_detail.html
{% extends "base.html" %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <h3>Country detail</h3>
                <table class="table table-bordered">
                    <tr class="head_text">
                        <td>
                            <h4>{{ country.common }}</h4>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table class="table table-bordered">
                                <tr>
                                    <th>Common name</th>
                                    <td>{{ country.common }}</td>
                                </tr>
                                <tr>
                                    <th>Official name</th>
                                    <td>{{ country.official }}</td>
                                </tr>
                                <tr>
                                    <th>Capital</th>
                                    <td>{{ country.capital }}</td>
                                </tr>
                                <tr>
                                    <th>Region</th>
                                    <td>{{ country.region }}</td>
                                </tr>
                                <tr>
                                    <th>Subregion</th>
                                    <td>{{ country.subregion }}</td>
                                </tr>
                                <tr>
                                    <th>Flag</th>
                                    <td><a href="{{ country.flag }}" target="_blank">
                                        <div class="image-frame">
                                            <img src="{{ country.flag }}" style="width: 100px" alt="Flag">
                                        </div>
                                    </a></td>
                                </tr>
                                <tr>
                                    <th>Map</th>
                                    <td><a href="{{ country.maps }}" target="_blank">Google Map</a></td>
                                </tr>
                            </table>
                            <div style="text-align: right">
                                <a href="{% url "movieapp:country_list" %}">List of countries</a>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

movieapp/templates/movieapp/country_list.html
{% extends "base.html" %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <h3>List of countries</h3>
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">&laquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                        </li>
                    {% endif %}

                    <li class="page-link text-dark">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </li>

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Country</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for country in countries %}
                        <tr>
                            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                            <td><a href="{% url "movieapp:country_detail" pk=country.id %}">{{ country }}</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

movieapp/templates/movieapp/index.html
{% extends 'base.html' %}
{% block main %}
    <h1>Movie staff</h1>
{% endblock %}

movieapp/templates/movieapp/movie_detail.html
{% extends "base.html" %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <h3>Movie detail</h3>
                <table class="table table-bordered">
                    <tr class="head_text">
                        <td>{{ movie.title }}</td>
                    </tr>
                    <tr>
                        <td>
                            <table class="table table-bordered">
                                <tr>
                                    <th>Title</th>
                                    <td>{{ movie.title }}</td>
                                </tr>
                                <tr>
                                    <th>Year</th>
                                    <td>{{ movie.year }}</td>
                                </tr>
                                <tr>
                                    <th>IMDB</th>
                                    <td><a href="https://www.imdb.com/title/{{ movie.imdb }}" target="_blank">IMDB</a>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Type</th>
                                    <td>{{ movie.type }}</td>
                                </tr>
                                {% if movie.poster and movie.poster != "NULL" %}
                                    <tr>
                                        <th>Poster</th>
                                        <td><a href="{{ movie.poster }}" target="_blank">
                                            <img src="{{ movie.poster }}" style="width: 100px" alt="poster">
                                        </a></td>
                                    </tr>
                                {% endif %}
                            </table>
                            <div style="text-align: right">
                                <a href="{% url "movieapp:movie_list" %}">List of movies</a>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

movieapp/templates/movieapp/movie_list.html
{% extends "base.html" %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">&laquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                        </li>
                    {% endif %}
                    <li class="page-link text-dark">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </li>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for movie in movies %}
                        <tr>
                            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                            <td><a href="{% url "movieapp:movie_detail" pk=movie.id %}">{{ movie.title }}</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

movieapp/templates/movieapp/search.html
{% extends 'base.html' %}

{% block main %}
    <div class="row">
        <form action="{% url 'movieapp:search_result' %}" method="get">
            <div class="col-8 mx-auto">
                <h1>Search</h1>
                <div class="row">
                    <div class="col-4">
                        <input type="text" class="form-control" id="site-search" name="search"
                               placeholder="Search prhase">
                    </div>
                    <div class="col-4">
                        <select name="table" id="table" class="form-select form-control" aria-label="Default select example">
                            <option value="country" selected>Country table</option>
                            <option value="movie">Movie table</option>
                        </select>
                    </div>
                    <div class="col-4">
                        <input type="submit" value="Search" class="btn btn-primary mb-3 form-control">
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

movieapp/templates/movieapp/search_result.html
{% extends 'base.html' %}
{% block main %}
    <div class="row">
        <div class="col-8 mx-auto">
            <div class="row">
                <h1>Search result</h1>
                {{ table }} <! -- context['table'] -->
                {% if object_list and table == 'country' %}
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Common name</th>
                            <th>Official name</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for country in object_list %}
                            <tr>
                                <td>{{ country.common }}</td>
                                <td>{{ country.official }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% elif table == 'movie' %}
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Year</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for movie in object_list %}
                            <tr>
                                <td>{{ movie.Title }}</td>
                                <td>{{ movie.Year }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="text-danger">No result found!</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bare - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        <!-- Page content-->
        <div class="container">
            {% include 'menu.html' %}
            <div class="row">
               {% block main %}

               {% endblock %}
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/menu.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'movieapp:index' %}">My Movies</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'movieapp:index' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="/admin">Admin</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'movieapp:search' %}">Search</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Lists</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url "movieapp:country_list" %}">Countries</a></li>
                        <li><a class="dropdown-item" href="{% url "movieapp:movie_list" %}">Movies</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>